name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main  # Change this to match your default branch

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Set previous commit variable
        run: |
          PREV_COMMIT=$(git rev-parse origin/main~1)
          echo "PREV_COMMIT=${PREV_COMMIT}" >> $GITHUB_ENV
          echo "Previous commit hash: ${PREV_COMMIT}"
        shell: bash

      - name: Run TruffleHog scan (Git mode)
        run: |
          docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest git file:///pwd --since-commit $PREV_COMMIT
