name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main  # Change this to match your default branch

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last two commits for comparison

      - name: Get list of changed files
        id: changed_files
        run: |
          git diff --name-only HEAD~1 HEAD > changed_files.txt
          cat changed_files.txt  # Print the list of changed files for debugging

      - name: Run TruffleHog on changed files
        run: |
          while IFS= read -r file; do
            # Run TruffleHog on the specific changed file
            docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest git file:///pwd --since-commit HEAD --path "$file"
          done < changed_files.txt
